name: test_django
dependencies:
- pip=9.0.1=py27_1
- python=2.7.11=5
- wheel=0.29.0=py27_0
- numpy=1.11.3=py27_0
- pip:
  - django==1.10.5
  - django-cors-headers==2.0.2
  - gspread==0.6.2
  - pygsheets==1.0.0
  - oauth2client==4.0.0

